### ISSUE TITLE
@flatfile/react override #root styles

### ISSUE THREAD

**Issue by david-tuix** [FlatFilers/react-adapter#100]
Hello.
I installed the `@flatfile/react` package but when importing the `usePortal` hook in a component, the styles of the whole application are overwritten. Some styles are applied globally and produce this bug.
Is it possible to have a fix for this?

**Comment by Arsik36** [comment]
Hey David, can you confirm which version of the package you have installed? Our latest version of the React SDK should have updated styles that do not override global styles and are flatfile-specific.

**Comment by david-tuix** [comment]
Thanks for replying, I updated the packages to use the latest versions. The issue with the styles was solved, but now I'm getting an error when open the Flatfile component. It looks like `languageOverride` and `translationsPath` as sent as null by Flatfile in a request

![image](https://github.com/FlatFilers/react-adapter/assets/108133302/28b5356d-0c5c-48f1-836e-ac7f7c51bc72)

and I'm getting this error:

![image](https://github.com/FlatFilers/react-adapter/assets/108133302/d277a5a2-f95a-475e-8f5f-6f225ba8d3de)

How can I solve this? are the `languageOverride` and `translationsPath` mandatory parameters now?


Versions:
`"@flatfile/react": "7.8.6"` 
`"@flatfile/api": "1.7.8"`
`"@flatfile/v2-shims": "1.1.2"`

**Comment by Arsik36** [comment]
Sorry about that, David! I'm seeing that too! Can you move back to version 7.8.5? We'll ticket this and it fixed!

**Comment by david-tuix** [comment]
Thank you Arseniy. I tested it with the 7.8.5 version and it worked 🙏.

**Comment by Arsik36** [comment]
Hye David, you are all good to upgrade to the latest. We solved the issue you previously saw with Translation errors

**Comment by david-tuix** [comment]
I tested the latest version of the package and everything is working well. Thank you for your support 🙌

**Comment by Arsik36** [comment]
Awesome, glad to hear it!
